repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: black
        language_version: python3
        files: ^backend/
        exclude: ^backend/app/iitsrc/Evaluation.ipynb

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        name: ruff
        args: [--fix]
        language_version: python3
        files: ^backend/
        exclude: ^backend/app/iitsrc/Evaluation.ipynb
