name: Deploy Frontend
 
on:
  push:
    branches:
      - devops/new-server
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - 'frontend/**'

env:
  NODE_VERSION: '16.17.1'


jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true || github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build
        run: npm run build
        working-directory: ./frontend

      - name: Store Dist Folder
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: ./frontend/dist

  deploy:
    needs: [ build ]
    runs-on: self-hosted
    environment: new-server
    
    steps:
      - name: Download Dist Folder
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: ${{ secrets.BUILD_PATH }}

      - name: Move build
        run: mv -v ${{ secrets.BUILD_PATH }} ${{ secrets.SERVE_PATH }}/releases/${GITHUB_RUN_ID}

      - name: Remove old link
        run: rm -rf ${{ secrets.SERVE_PATH }}/current

      - name: Create new symlink
        run: ln -s ${{ secrets.SERVE_PATH }}/releases/${GITHUB_RUN_ID} ${{ secrets.SERVE_PATH }}/current 