# name: Backend Deployment

# on:
#   #workflow_run:
#   #  workflows: [ "Build Docker Image" ]
#   #  types: [ completed ]
#   #  branches: [ main ]
#   push:
#     branches:
#       - devops-deploy-test-branch

# jobs:
#   restart-development:
#     runs-on: self-hosted
#     environment: development

#     steps:
#       - name: Add SSH private key
#         run: |
#           mkdir -p ~/.ssh
#           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
#           chmod 600 ~/.ssh/id_ed25519
    
#       - name: Add SSH server to known hosts
#         run: |
#           ssh-keyscan -H ${{ secrets.SSH_SERVER }} >> ~/.ssh/known_hosts
    
#       - name: Restart service on remote server
#         run: |
#           ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_SERVER }} "sudo systemctl restart app.service > /tmp/restart_service.log 2>&1" 